{
 "title": "Payment Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(paymenthttp_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(paymenthttp_request_duration_seconds_count,instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(paymenthttp_request_duration_seconds_count,route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic - Req/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(rate(paymenthttp_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])) by (job)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{ job }}",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Traffic - Req/s by handler",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(rate(paymenthttp_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])) by (job, method, route)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{ job }} - {{ method }} {{handler}}",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors - % (5xx)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(rate(paymenthttp_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\", code=\"500\"}[$__rate_interval])) by (job)/sum(rate(paymenthttp_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[$__rate_interval])) by (job)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{ job }}",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Errors - % by handler (5xx)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "sum(rate(paymenthttp_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\", code=\"500\"}[$__rate_interval])) by (job, method, route)/sum(rate(paymenthttp_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[$__rate_interval])) by (job, method, route)",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{ job }} - {{ method }} {{route}}",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Latêncy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency - General",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "histogram_quantile(0.5, sum by (job, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{ job }} - p50",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "expr": "histogram_quantile(0.95, sum by (job, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "legendFormat": "{{ job }} - p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "legendFormat": "{{ job }} - p99"
      }
     ]
    },
    {
     "title": "Latency by handler",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "histogram_quantile(0.5, sum by (job, method, route, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{ job }} - {{ method }} {{ route }} - p50",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "expr": "histogram_quantile(0.95, sum by (job , method, route, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "legendFormat": "{{ job }} - {{ method }} {{ route }} - p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, method, route, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "legendFormat": "{{ job }} - {{ method }} {{ route }} - p99"
      }
     ]
    },
    {
     "title": "Latency by instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "histogram_quantile(0.5, sum by (job, instance, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "{{ job }} - {{ instance }} - p50",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "expr": "histogram_quantile(0.95, sum by (job, instance, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "legendFormat": "{{ job }} - {{ instance }} - p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate(paymenthttp_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", route=~\"$handler\"}[5m])))",
       "legendFormat": "{{ job }} - {{ instance }} - p99"
      }
     ]
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "bullmq_job_count{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} {{state}}"
      }
     ]
    }
   ]
  }
 ]
}