{
 "title": "Pod Detail",
 "description": "Kubernetes Pod",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "NameSpace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{container=~\"$Container\",namespace=~\"$NameSpace\"},pod)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$Pod\"},node)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(container_fs_reads_bytes_total{container=~\"$Container\",instance=\"$Node\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Realtime statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "DataSource" },
  {
   "title": "Mem Usage Statistics",
   "type": "piechart",
   "description": "容器内存使用实时统计",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{container=~\"$Container\",instance=\"$Node\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(container_memory_rss{container=~\"$Container\",instance=\"$Node\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_cache{container=~\"$Container\",instance=\"$Node\"})",
     "legendFormat": "Cache"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"$Container\",instance=\"$Node\"})",
     "legendFormat": "Working"
    }
   ]
  },
  {
   "title": "load 10s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_load_average_10s{container=\"$Container\",instance=\"$Node\"})"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container=\"$Container\",node=\"$Node\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container=\"$Container\",node=\"$Node\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "machine_cpu_cores{instance=\"$Node\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container=\"$Container\",instance=\"$Node\"})by(device)",
     "legendFormat": "{{device}}: usage"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{container=\"$Container\",instance=\"$Node\"}[5m]))by(device)",
     "legendFormat": "{{device}}: read"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{container=\"$Container\",instance=\"$Node\"}[5m]))by(device)",
     "legendFormat": "{{device}}: wirte"
    }
   ]
  },
  {
   "title": "transmit_rate(1m)",
   "type": "gauge",
   "description": "容器在1分钟内流出的平均速率",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$Pod\",instance=\"$Node\",interface=\"eth0\"}[2m]))by(pod)"
    }
   ]
  },
  {
   "title": "receive_rate(1m)",
   "type": "gauge",
   "description": "容器在1分钟内接收的平均速率",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$Pod\",instance=\"$Node\",interface=\"eth0\"}[2m]))by(pod)"
    }
   ]
  },
  {
   "title": "CPU Usage Statistics",
   "type": "piechart",
   "description": "容器CPU使用实时统计",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{container=\"$Container\",instance=\"$Node\"}[5m])*100)",
     "legendFormat": "User"
    },
    {
     "expr": "sum(irate(container_cpu_system_seconds_total{container=\"$Container\",instance=\"$Node\"}[5m])*100)",
     "legendFormat": "System"
    },
    {
     "expr": "100 - (sum(irate(container_cpu_system_seconds_total{container=\"$Container\",instance=\"$Node\"}[5m])*100) + sum(irate(container_cpu_user_seconds_total{container=\"$Container\",instance=\"$Node\"}[5m])*100))",
     "legendFormat": "idel"
    }
   ]
  },
  {
   "title": "network packet in/out(1m)",
   "type": "piechart",
   "description": "容器在1分钟内网络数据包的传输统计",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_network_receive_packets_total{pod=~\"$Container.+\",instance=\"$Node\",interface=\"eth0\"})",
     "legendFormat": "receive: total"
    },
    {
     "expr": "sum(container_network_receive_errors_total{pod=~\"$Container.+\",instance=\"$Node\",interface=\"eth0\"})",
     "legendFormat": "receive: error"
    },
    {
     "expr": "sum(container_network_receive_packets_dropped_total{pod=~\"$Container.+\",instance=\"$Node\",interface=\"eth0\"})",
     "legendFormat": "receive: dropped"
    },
    {
     "expr": "sum(container_network_transmit_packets_total{pod=~\"$Container.+\",instance=\"$Node\",interface=\"eth0\"})",
     "legendFormat": "transmit: total"
    },
    {
     "expr": "sum(container_network_transmit_errors_total{pod=~\"$Container.+\",instance=\"$Node\",interface=\"eth0\"})",
     "legendFormat": "transmit: error"
    },
    {
     "expr": "sum(container_network_transmit_packets_dropped_total{pod=~\"$Container.+\",instance=\"$Node\",interface=\"eth0\"})",
     "legendFormat": "transmit: dropped"
    }
   ]
  },
  {
   "title": "Memory_failcnt",
   "type": "stat",
   "description": "Number of memory usage hits limits  \n内存使用命中limits的次数",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_failcnt{container=~\"$Container\",instance=\"$Node\"})"
    }
   ]
  },
  {
   "title": "Memory_failures",
   "type": "table",
   "description": "容器在10分钟内新增申请内存失败的次数\n\nThe following statistics are only available by kernels from 2.6 \npgfault     –  Number of page faults the system has made per second (minor + major)  \npgmajfault  –  Number of major faults per second the system required loading a memory page from disk",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(increase(container_memory_failures_total{container=~\"$Container\",failure_type=\"pgfault\",instance=\"$Node\"}[10m]))",
     "legendFormat": "pgfault"
    },
    {
     "expr": "avg(increase(container_memory_failures_total{container=~\"$Container\",failure_type=\"pgmajfault\",instance=\"$Node\"}[10m]))",
     "legendFormat": "pgmajfault"
    }
   ]
  },
  {
   "title": "disk R/W size",
   "type": "table",
   "description": "磁盘读写数据统计",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_reads_bytes_total{container=\"$Container\",instance=\"$Node\",device=\"$device\"})",
     "legendFormat": "read_bytes"
    },
    {
     "expr": "sum(container_fs_writes_bytes_total{container=\"$Container\",instance=\"$Node\",device=\"$device\"})",
     "legendFormat": "wirte_bytes"
    }
   ]
  },
  {
   "title": "disk io",
   "type": "table",
   "description": "当前I/O队列个数及请求等待时间",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(container_fs_io_current{container=\"$Container\",instance=\"$Node\"})",
     "legendFormat": "IO Count"
    },
    {
     "expr": "avg(container_fs_io_time_seconds_total{container=\"$Container\",instance=\"$Node\"})",
     "legendFormat": "IO Time"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_start_time{namespace=\"$NameSpace\",pod=\"$Pod\"}*1000)by(namespace,pod)"
    },
    {
     "expr": "sum(container_start_time_seconds{namespace=\"$NameSpace\",container=\"$Container\",pod=\"$Pod\",instance=\"$Node\"}*1000)by(namespace,container,pod,__name__,instance)"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$NameSpace\",pod=\"$Pod\"})by(namespace,pod)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_file_descriptors{container=\"$Container\",instance=\"$Node\"})by(__name__,pod,instance)",
     "legendFormat": "file descriptior"
    },
    {
     "expr": "sum(container_sockets{container=\"$Container\",instance=\"$Node\"})by(__name__,pod,instance)",
     "legendFormat": "sockets"
    },
    {
     "expr": "sum(container_processes{container=\"$Container\",instance=\"$Node\"})by(__name__,pod,instance)",
     "legendFormat": "processes"
    },
    {
     "expr": "sum(container_threads{container=\"$Container\",instance=\"$Node\"})by(__name__,pod,instance)",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{container=\"$Container\"})by(__name__,container)",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{container=\"$Container\"})by(__name__,container)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{container=\"$Container\"})by(__name__,container)",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{container=\"$Container\"})by(__name__,container)",
     "legendFormat": "terminated"
    }
   ]
  },
  { "title": "Container usage chart", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$Container\",instance=\"$Node\",pod=\"$Pod\"}[5m])*100)by(pod) / sum(kube_pod_container_resource_limits_cpu_cores{container=\"$Container\",node=\"$Node\",pod=\"$Pod\"})by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=\"$Container\",instance=\"$Node\",pod=\"$Pod\"}/container_spec_memory_limit_bytes{container=\"$Container\",instance=\"$Node\",pod=\"$Pod\"}*100)by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$Pod\",instance=\"$Node\",interface=\"eth0\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}: transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$Pod\",instance=\"$Node\",interface=\"eth0\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}: receive"
    }
   ]
  },
  {
   "title": "disk R/W rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{container=~\"$Container\",pod=\"$Pod\",instance=\"$Node\",device=\"$device\"}[5m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: read"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{container=~\"$Container\",pod=\"$Pod\",instance=\"$Node\",device=\"$device\"}[5m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: write"
    }
   ]
  },
  {
   "title": "disk R/W iops",
   "type": "timeseries",
   "description": "容器一分钟平均完成的IO次数",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{container=\"$Container\",pod=\"$Pod\",instance=\"$Node\",device=\"$device\"}[2m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: read_iops"
    },
    {
     "expr": "sum(irate(container_fs_writes_total{container=\"$Container\",pod=\"$Pod\",instance=\"$Node\",device=\"$device\"}[2m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: write_iops"
    }
   ]
  },
  {
   "title": "disk IO time",
   "type": "timeseries",
   "description": "容器在1分钟内平均每次IO等待的时间",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_write_seconds_total{container=\"$Container\",pod=\"$Pod\",instance=\"$Node\",device=\"$device\"}[2m]))by(device,pod)",
     "legendFormat": "{{pod}} - {{device}}: write_iops"
    },
    {
     "expr": "sum(irate(container_fs_read_seconds_total{container=\"$Container\",pod=\"$Pod\",instance=\"$Node\",device=\"$device\"}[2m]))by(device)",
     "legendFormat": "{{pod}} - {{device}}: read_iops"
    }
   ]
  }
 ]
}