{
 "title": "Sanity Check",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Comparison", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability - Redis vs DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ticket_app_redis_availability{status=\"available\"} - ticket_app_db_availability{status=\"available\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ticket_app_redis_availability{status=\"unavailable\"} - ticket_app_db_availability{status=\"unavailable\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ticket_app_redis_availability{status=\"total\"} - ticket_app_db_availability{status=\"total\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Redis Dropper vs DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ticket_app_redis_dropper{status=\"available\"} - ticket_app_db_availability{status=\"available\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ticket_app_redis_dropper{status=\"unavailable\"} - ticket_app_db_availability{status=\"unavailable\"}",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ticket_app_redis_dropper{status=\"total\"} - ticket_app_db_availability{status=\"total\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DB Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "ticket_app_db_availability", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Redis Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "ticket_app_redis_availability", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Dropper Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "ticket_app_redis_dropper", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Double Booking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "ticket_app_double_order", "legendFormat": "Double Book" }
   ]
  }
 ]
}