{
 "title": "Ticket Flow Control",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(dropper_async_order_processor_limiter_inflight_histogram_bucket,pod)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Queue Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(dropper_async_order_processor_limiter_order_processor_limiter_window_queue_size_histogram_count{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inflight Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(dropper_async_order_processor_limiter_inflight_histogram_bucket{pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Percentile 99 - {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(dropper_async_order_processor_limiter_inflight_histogram_bucket{pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Percentile 95 - {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(dropper_async_order_processor_limiter_inflight_histogram_bucket{pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Percentile 75 - {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(dropper_async_order_processor_limiter_inflight_histogram_bucket{pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Percentile 50 - {{pod}}"
      }
     ]
    },
    {
     "title": "Inflight Requests Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(dropper_async_order_processor_limiter_inflight_histogram_count{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dropped Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dropped Requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(dropper_async_order_processor_limiter_order_processor_limiter_dropped{pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "Dropped"
      }
     ]
    },
    {
     "title": "RTT Percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(pod, le) (rate(dropper_async_order_processor_limiter_order_processor_limiter_rtt_timer_bucket{pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Percentile 99 {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(pod, le) (rate(dropper_async_order_processor_limiter_order_processor_limiter_rtt_timer_bucket{pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Percentile 95 {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(pod, le) (rate(dropper_async_order_processor_limiter_order_processor_limiter_rtt_timer_bucket{pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Percentile 75 {{pod}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(pod, le) (rate(dropper_async_order_processor_limiter_order_processor_limiter_rtt_timer_bucket{pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "Percentile 50 {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}