/*
Payment Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mock_payment

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InvoicesIdGet404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoicesIdGet404Response{}

// InvoicesIdGet404Response struct for InvoicesIdGet404Response
type InvoicesIdGet404Response struct {
	Message string `json:"message"`
}

type _InvoicesIdGet404Response InvoicesIdGet404Response

// NewInvoicesIdGet404Response instantiates a new InvoicesIdGet404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoicesIdGet404Response(message string) *InvoicesIdGet404Response {
	this := InvoicesIdGet404Response{}
	this.Message = message
	return &this
}

// NewInvoicesIdGet404ResponseWithDefaults instantiates a new InvoicesIdGet404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoicesIdGet404ResponseWithDefaults() *InvoicesIdGet404Response {
	this := InvoicesIdGet404Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *InvoicesIdGet404Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *InvoicesIdGet404Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *InvoicesIdGet404Response) SetMessage(v string) {
	o.Message = v
}

func (o InvoicesIdGet404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoicesIdGet404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *InvoicesIdGet404Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvoicesIdGet404Response := _InvoicesIdGet404Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvoicesIdGet404Response)

	if err != nil {
		return err
	}

	*o = InvoicesIdGet404Response(varInvoicesIdGet404Response)

	return err
}

type NullableInvoicesIdGet404Response struct {
	value *InvoicesIdGet404Response
	isSet bool
}

func (v NullableInvoicesIdGet404Response) Get() *InvoicesIdGet404Response {
	return v.value
}

func (v *NullableInvoicesIdGet404Response) Set(val *InvoicesIdGet404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoicesIdGet404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoicesIdGet404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoicesIdGet404Response(val *InvoicesIdGet404Response) *NullableInvoicesIdGet404Response {
	return &NullableInvoicesIdGet404Response{value: val, isSet: true}
}

func (v NullableInvoicesIdGet404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoicesIdGet404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


