
releases:
  - name: rabbitmq
    chart: oci://registry-1.docker.io/bitnamicharts/rabbitmq
    namespace: default
    version: 16.0.1
    values:
      - resourcesPreset: "nano"
      - metrics:
          enabled: true
      - auth:
          username: tugas-akhir
          password: tugas-akhir
          securePassword: false