
releases:
  - name: rabbitmq
    chart: oci://registry-1.docker.io/bitnamicharts/rabbitmq
    namespace: default
    version: 16.0.1
    values:
      - resources:
          requests:
            cpu: "0.25"
            memory: "512Mi"
          limits:
            cpu: "0.5"
            memory: "768Mi"
      - metrics:
          enabled: true
      - auth:
          username: tugas-akhir
          password: tugas-akhir
          securePassword: false