# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6370:6379"
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-0'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_EXTRA_FLAGS=--maxmemory 2gb --maxmemory-policy allkeys-lru'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6371:6379"
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-1'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_EXTRA_FLAGS=--maxmemory 2gb --maxmemory-policy allkeys-lru'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.4
    ports:
      - "6372:6379"
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=0'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_ANNOUNCE_HOSTNAME=redis-node-2'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6379'
      - 'REDIS_CLUSTER_PREFERRED_ENDPOINT_TYPE=hostname'
      - 'REDIS_EXTRA_FLAGS=--maxmemory 2gb --maxmemory-policy allkeys-lru'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local