{
 "title": "Patroni",
 "description": "Patroni dashboard for pgSCV metrics (Prometheus version, pgSCV 0.9.7 edition)",
 "tags": [ "pgSCV" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "DS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(patroni_version,instance)"
    }
   },
   {
    "name": "patroni",
    "label": "Patroni",
    "query": {
     "query": "label_values(patroni_version{instance=\"$instance\"},kubernetes_service_name)"
    }
   },
   {
    "name": "scope",
    "label": "Scope",
    "query": {
     "query": "label_values(patroni_postgres_running{kubernetes_service_name=\"$patroni\"},scope)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Patroni overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DCS last seen",
   "type": "stat",
   "description": "Epoch timestamp when DCS was last contacted successfully by Patroni.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_dcs_last_seen{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica",
   "type": "stat",
   "description": "Is replica.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_replica{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replay paused",
   "type": "stat",
   "description": "Is 1 if the replaying of Postgres transaction log is paused, 0 otherwise.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_xlog_paused{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Standby leader",
   "type": "stat",
   "description": "Is standby leader.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_standby_leader{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster lock",
   "type": "stat",
   "description": "Patroni cluster lock status.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_cluster_unlocked{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pause/Resume mode",
   "type": "stat",
   "description": "Patroni pause or resume mode for the cluster.\n\nSee docs https://patroni.readthedocs.io/en/master/pause.html for more info.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_is_paused{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PostgreSQL overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "PostgreSQL running",
   "type": "stat",
   "description": "Is 1 if Postgres is running, 0 otherwise.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_running{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL synchronous standby",
   "type": "stat",
   "description": "Is 1 if synchronous mode is active, 0 if inactive.\n\nSee docs https://patroni.readthedocs.io/en/latest/replication_modes.html#synchronous-mode for more info.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_sync_standby{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL pending restart",
   "type": "stat",
   "description": "Is 1 if the node needs a restart, 0 otherwise.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_pending_restart{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL timeline",
   "type": "stat",
   "description": "PostgreSQL timeline.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_timeline{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL version",
   "type": "stat",
   "description": "PostgreSQL version.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_server_version{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL streaming",
   "type": "stat",
   "description": "Is 1 if Postgres is streaming, 0 otherwise.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_streaming{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL is archive recovery",
   "type": "stat",
   "description": "Is 1 if Postgres is replicating from archive, 0 otherwise.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "patroni_postgres_in_archive_recovery{instance=\"$instance\",kubernetes_service_name=\"$patroni\",scope=\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PostgreSQL WAL info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Primary WAL location",
   "type": "timeseries",
   "description": "Current location of the Postgres transaction log, 0 if this node is a replica.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "patroni_xlog_location{instance=\"$instance\",scope=\"$scope\"}",
     "legendFormat": "{{service_id}}"
    }
   ]
  },
  {
   "title": "Replica received WAL location",
   "type": "timeseries",
   "description": "Current location of the received Postgres transaction log, 0 if this node is the leader.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "patroni_xlog_received_location{instance=\"$instance\",scope=\"$scope\"}",
     "legendFormat": "{{service_id}}"
    }
   ]
  },
  {
   "title": "Replica replayed WAL location",
   "type": "timeseries",
   "description": "Current location of the replayed Postgres transaction log, 0 if this node is the leader.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "patroni_xlog_replayed_location{instance=\"$instance\",scope=\"$scope\"}",
     "legendFormat": "{{service_id}}"
    }
   ]
  }
 ]
}