{
 "title": "Redis Cluster",
 "description": "Dashboard is showing state and configuration for Redis cluster",
 "tags": [
  "Redis",
  "Keydb",
  "Cache"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(redis_up,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance status",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_up{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_uptime_in_seconds{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis slave status",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "redis_slave_info{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis slave priority",
   "type": "table",
   "description": "The priority of the instance as a candidate for failover",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "redis_slave_priority{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster enabled",
   "type": "table",
   "description": "Indicate Redis cluster is enabled",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "redis_cluster_enabled{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Master link status",
   "type": "table",
   "description": "Status of the link (up/down)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "redis_master_link_up{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master syncing",
   "type": "table",
   "description": "Indicate the master is syncing to the replica",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "redis_master_sync_in_progress{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Master replica offset",
   "type": "timeseries",
   "description": "The server's current replication offset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_master_repl_offset{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Second replica offset",
   "type": "timeseries",
   "description": "The offset up to which replication IDs are accepted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_second_repl_offset{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slave replica offset",
   "type": "timeseries",
   "description": "The replication offset of the replica instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_slave_repl_offset{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Master last IO seconds",
   "type": "timeseries",
   "description": "Number of seconds since the last interaction with master",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{namespace=\"$namespace\"}",
     "legendFormat": "Instance {{instance}} || Master host: {{master_host}}:{{master_port}}"
    }
   ]
  },
  { "title": "Backlog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Backlog is active",
   "type": "table",
   "description": "Flag indicating replication backlog is active",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "redis_repl_backlog_is_active{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backlog size",
   "type": "timeseries",
   "description": "Total size in bytes of the replication backlog buffer",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_replication_backlog_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backlog history size",
   "type": "timeseries",
   "description": "Size in bytes of the data in the replication backlog buffer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_repl_backlog_history_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Master backlog offset",
   "type": "timeseries",
   "description": "The master offset of the replication backlog buffer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_repl_backlog_first_byte_offset{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}