{
 "title": "Ticket Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ticket_backend_echo_requests_total, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ticket_backend_echo_requests_total, instance)"
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(ticket_backend_echo_requests_total,url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    rate(\n      ticket_backend_echo_requests_total{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        url=~\"$handler\"\n      }[$__rate_interval]\n    )\n  ), 0.001\n)\n"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(ticket_backend_echo_requests_total{code=~\"2.+\", instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "3XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(ticket_backend_echo_requests_total{code=~\"3.+\", instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(ticket_backend_echo_requests_total{instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])) by(code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(ticket_backend_echo_requests_total{code=~\"4.+\", instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(ticket_backend_echo_requests_total{code=~\"5.+\", instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Success Rate (non 4-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    ticket_backend_echo_requests_total{\n      job=~\"$job\",\n      instance=~\"$instance\",\n      url=~\"$handler\",\n      code!~\"[4-5].*\"\n    }[$__rate_interval]\n  )\n) /\nsum(\n  rate(\n    ticket_backend_echo_requests_total{\n      job=~\"$job\",\n      instance=~\"$instance\",\n      url=~\"$handler\",\n    }[$__rate_interval]\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Request Latency (P95)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum (\n    irate(\n      ticket_backend_echo_request_duration_seconds_bucket{\n        job=~\"$job\",\n        instance=~\"$instance\",\n        url=~\"$handler\"\n      }[$__rate_interval]\n    )\n  ) by (job, le)\n)\n"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Traffic - Req/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(ticket_backend_echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[2m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic - Req/s by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(ticket_backend_echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[2m])) by (job, method, url)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{url}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Errors - % (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(ticket_backend_echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\", code=\"5.+\"}[$__rate_interval])) by (job)/sum(rate(ticket_backend_echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors - % by handler (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(ticket_backend_echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\", code=\"500\"}[$__rate_interval])) by (job, method, url)/sum(rate(ticket_backend_echo_requests_total{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])) by (job, method, url)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{url}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Latêncy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Latency - General",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])))",
     "legendFormat": "{{ job }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])))",
     "legendFormat": "{{ job }} - p99"
    }
   ]
  },
  {
   "title": "Latency by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, method, url, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job , method, url, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])))",
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, method, url, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])))",
     "legendFormat": "{{ job }} - {{ method }} {{ url }} - p99"
    }
   ]
  },
  {
   "title": "Latency by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, instance, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[$__rate_interval])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ instance }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, instance, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate(ticket_backend_echo_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", url=~\"$handler\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p99"
    }
   ]
  }
 ]
}