repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    chart: grafana/grafana
    namespace: monitoring
    version: 8.13.1
    values:
      - persistence:
          type: pvc
          enabled: true
          size: 10Gi
        adminPassword: tugas-akhir
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://loki-gateway.monitoring.svc.cluster.local
  - name: loki
    chart: grafana/loki
    namespace: monitoring
    version: 6.29.0
    set:
      - name: loki.auth_enabled
        value: false
    values:
      - loki:
          commonConfig:
            replication_factor: 3
          schemaConfig:
            configs:
              - from: "2025-04-24"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          pattern_ingester:
              enabled: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
          ruler:
            enable_api: true
      - minio:
          enabled: true      
      - deploymentMode: SingleBinary
      - singleBinary:
          replicas: 2
      - backend:
          replicas: 0
      - read:
          replicas: 0
      - write:
          replicas: 0
      - ingester:
          replicas: 0
      - querier:
          replicas: 0
      - queryFrontend:
          replicas: 0
      - queryScheduler:
          replicas: 0
      - distributor:
          replicas: 0
      - compactor:
          replicas: 0
      - indexGateway:
          replicas: 0
      - bloomCompactor:
          replicas: 0
      - bloomGateway:
          replicas: 0