gantt
    dateFormat  YYYY-MM-DD
    title       Jadwal Pengerjaan Tugas Akhir

    section Perencanaan dan desain solusi
    Menganalisis kebutuhan sistem                                                : r1, 2025-02-01, 5d
    Merancang rencana implementasi baseline architecture                         : r2, after r1, 5d
    Merancang rencana implementasi arsitektur pengoptimalan PostgreSQL           : r3, after r2, 5d
    Merancang rencana implementasi arsitektur event-driven                       : r4, after r3, 5d
    Merancang uji kasus                                                          : r5, after r4, 5d

    section Implementasi
    Merancang skema basis data                                                   : i1, after r5, 3d
    Mengimplementasikan user service                                             : i2, after i1, 3d
    Mengimplementasikan payment service                                          : i3, after i2, 3d
    Mengimplementasikan ticketing service                                        : i4, after i3, 6d
    Mengintegrasikan penggunaan extension PostgreSQL Citus                       : i5, after i4, 6d
    Mengintegrasikan Redpanda untuk queue based load leveling                    : i6, after i5, 6d
    Mengimplementasikan drop-request berdasarkan pending reservation             : i7, after i6, 4d
    Mengintegrasikan RisingWave untuk incrementally updated query                : i8, after i7, 6d
    Merancang dan mengimplementasikan skema topic untuk event-driven architecture: i9, after i8, 6d
    Mengintegrasikan RisingWave untuk event-driven architecture                  : i10, after i9, 6d
    Mengimplementasikan ticketing service versi event-driven architecture        : i11, after i10, 8d

    section Deployment dan Pengujian
    Deployment baseline architecture              : d1, after i11, 3d
    Pengujian baseline architecture               : d2, after d1, 3d
    Deployment arsitektur pengoptimalan PostgreSQL: d3, after d2, 3d
    Pengujian arsitektur pengoptimalan PostgreSQL : d4, after d3, 3d
    Deployment arsitektur event-driven            : d5, after d4, 3d
    Pengujian arsitektur event-driven             : d6, after d5, 3d

    section Evaluasi dan Pengolahan Data
    Pengolahan data                               : e1, after d6, 7d
    Menyelesaikan laporan tugas akhir             : e2, after e1, 10d
