apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
    spec:
      containers:
      - name: payment-server
        image: registry.localhost:5001/tugas-akhir/payment-server:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - name: tls
          mountPath: "/etc/tls"
          readOnly: true
        env:
        - name: REDIS_HOSTS
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: redis-hosts
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: redis-password
        - name: NODE_ENV
          value: production
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: webhook-url
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: webhook-secret
        - name: KEY_PATH
          value: /etc/tls/tls.key
        - name: CERT_PATH
          value: /etc/tls/tls.crt
      - name: payment-notifier
        image: registry.localhost:5001/tugas-akhir/payment-notifier:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: tls
          mountPath: "/etc/tls"
          readOnly: true
        env:
        - name: REDIS_HOSTS
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: redis-hosts
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: redis-password
        - name: NODE_ENV
          value: production
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: webhook-url
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: webhook-secret
        - name: KEY_PATH
          value: /etc/tls/tls.key
        - name: CERT_PATH
          value: /etc/tls/tls.crt
      volumes:
      - name: tls
        secret:
          secretName: service-tls
---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics-queue'
    prometheus.io/port: '3000'
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  labels:
    app: payment
type: Opaque
data:
  redis-hosts: cmVkaXMtcmVkaXMtY2x1c3Rlci0wLnJlZGlzLXJlZGlzLWNsdXN0ZXItaGVhZGxlc3MucGF5bWVudC5zdmMuY2x1c3Rlci5sb2NhbDo2Mzc5LHJlZGlzLXJlZGlzLWNsdXN0ZXItMS5yZWRpcy1yZWRpcy1jbHVzdGVyLWhlYWRsZXNzLnBheW1lbnQuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OSxyZWRpcy1yZWRpcy1jbHVzdGVyLTIucmVkaXMtcmVkaXMtY2x1c3Rlci1oZWFkbGVzcy5wYXltZW50LnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzk=
  redis-password: cGFzc3dvcmQ=
  webhook-url: todo
  webhook-secret: c2VjcmV0
