apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-run-${RUN_ID}
spec:
  parallelism: 10
  script:
    configMap:
      name: ticket-code
      file: ticket.js
  arguments: -o experimental-prometheus-rw --include-system-env-vars
  runner:
    image: haiakbar/ta-agent:latest
    resources:
      limits:
        cpu: "4"
        memory: "8Gi"
      requests:
        cpu: "4"
        memory: "8Gi"
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "http://prometheus-server.monitoring.svc.cluster.local/api/v1/write"
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: "true"
      - name: RUN_ID
        value: ${RUN_ID}
      - name: VARIANT
        value: ${VARIANT}
      - name: HOST_FORWARD
        value: ${HOST_FORWARD}
