# reference https://github.com/citusdata/docker/blob/master/README.md
services:
  master:
    container_name: "citus_master"
    image: "citusdata/citus:13.0.1-pg16"
    ports:
      - "5000:5432"
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "tugasakhir"
      PGUSER: "postgres"
      PGPASSWORD: "tugasakhir"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  worker_1:
    image: "citusdata/citus:13.0.1-pg16"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  worker_2:
    image: "citusdata/citus:13.0.1-pg16"
    labels: [ "com.citusdata.role=Worker" ]
    depends_on: [ manager ]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  manager:
    container_name: "citus_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH
volumes:
  healthcheck-volume: