// This file is auto-generated by @hey-api/openapi-ts

export type Invoice = {
	id: string;
	amount: number;
	description?: string;
	externalId: string;
	createdAt: string | null;
	expiredAt: string | null;
	paidAt: string | null;
	paidAmount: number | null;
	status: "pending" | "expired" | "paid" | "failed";
};

export type CreateInvoiceRequest = {
	amount: number;
	description?: string;
	externalId: string;
};

export type PayInvoiceRequest = {
	mode: "success" | "failed";
};

export type GetInvoicesByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: "/invoices/{id}";
};

export type GetInvoicesByIdErrors = {
	/**
	 * Invoice not found
	 */
	404: {
		message: string;
	};
};

export type GetInvoicesByIdError =
	GetInvoicesByIdErrors[keyof GetInvoicesByIdErrors];

export type GetInvoicesByIdResponses = {
	/**
	 * Retrieve the invoice
	 */
	200: Invoice;
};

export type GetInvoicesByIdResponse =
	GetInvoicesByIdResponses[keyof GetInvoicesByIdResponses];

export type PostInvoicesData = {
	body?: CreateInvoiceRequest;
	path?: never;
	query?: never;
	url: "/invoices";
};

export type PostInvoicesResponses = {
	/**
	 * Retrieve the invoice
	 */
	200: Invoice;
};

export type PostInvoicesResponse =
	PostInvoicesResponses[keyof PostInvoicesResponses];

export type PostInvoicesByIdPaymentData = {
	body?: PayInvoiceRequest;
	path: {
		id: string;
	};
	query?: never;
	url: "/invoices/{id}/payment";
};

export type PostInvoicesByIdPaymentErrors = {
	/**
	 * Bad request
	 */
	400: {
		message: string;
	};
	/**
	 * Invoice not found
	 */
	404: {
		message: string;
	};
};

export type PostInvoicesByIdPaymentError =
	PostInvoicesByIdPaymentErrors[keyof PostInvoicesByIdPaymentErrors];

export type PostInvoicesByIdPaymentResponses = {
	/**
	 * Retrieve the invoice
	 */
	200: Invoice;
};

export type PostInvoicesByIdPaymentResponse =
	PostInvoicesByIdPaymentResponses[keyof PostInvoicesByIdPaymentResponses];

export type ClientOptions = {
	baseUrl: "{protocol}://{server}" | (string & {});
};
