repositories:
  - name: yugabytedb
    url: https://charts.yugabyte.com

releases:
  - name: yugabytedb
    chart: yugabytedb/yugabyte
    namespace: default
    version: 2024.2.2
    values:
      - yugabytedUi:
          enabled: false  
      - gflags:
          tserver:
            ysql_output_buffer_size: "4194304"
      - storage:
          ephemeral: true
          master:
            count: 2
            size: 5Gi
            storageClass: standard
          tserver:
            count: 2
            size: 5Gi
            storageClass: standard
      - resource:
          master:
            requests:
              cpu: "0.5"
              memory: "1Gi"
            limits:
              cpu: "0.5"
              memory: "1Gi"
          tserver:
            requests:
              cpu: "1.5"
              memory: "3.5Gi"
            limits:
              cpu: "1.5"
              memory: "3.5Gi"
      - replicas:
          master: 3
          tserver: 3
      - partition:
          master: 3
          tserver: 3
      - master:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - "yb-master"
                topologyKey: kubernetes.io/hostname
      - tserver:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - "yb-tserver"
                topologyKey: kubernetes.io/hostname
  - name: pgbouncer
    namespace: default
    chart: oci://ghcr.io/icoretech/charts/pgbouncer
    version: 2.7.0
    values:
      - config:
          adminUser: admin
          adminPassword: tugas-akhir
          databases:
            yugabyte:
              host: yb-tserver-0.yb-tservers.default.svc.cluster.local,yb-tserver-1.yb-tservers.default.svc.cluster.local
              port: 5433 
              dbname: yugabyte 
              user: yugabyte 
          userlist:
            yugabyte: yugabyte
          pgbouncer:
            auth_type: md5
            pool_mode: transaction
            max_client_conn: 10000
            default_pool_size: 180
            reserve_pool_size: 20
            reserve_pool_timeout: 2
            log_connections: 0
            log_disconnections: 0
            log_pooler_errors: 1
            log_stats: 0
            ignore_startup_parameters: search_path,extra_float_digits
      - pgbouncerExporter:
          enabled: true