repositories:
  - name: yugabytedb
    url: https://charts.yugabyte.com
  - name: xxl-job-admin  
    url: https://dellnoantechnp.github.io/helm-chart-xxl-job-admin

releases:
  - name: yugabytedb
    chart: yugabytedb/yugabyte
    namespace: default
    version: 2024.2.2
    values:
      - yugabytedUi:
          enabled: false  
      - gflags:
          tserver:
            ysql_output_buffer_size: "4194304"
      - storage:
          ephemeral: true
          master:
            count: 2
            size: 5Gi
            storageClass: standard
          tserver:
            count: 2
            size: 5Gi
            storageClass: standard
      - resource:
          master:
            requests:
              cpu: "0.5"
              memory: "1Gi"
            limits:
              cpu: "0.5"
              memory: "1Gi"
          tserver:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      - replicas:
          master: 3
          tserver: 3
      - partition:
          master: 3
          tserver: 3
      - master:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - "yb-master"
                topologyKey: kubernetes.io/hostname
      - tserver:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - "yb-tserver"
                topologyKey: kubernetes.io/hostname
  - name: pgcat
    namespace: default
    chart: xxl-job-admin/pgcat
    version: 0.3.2
    values:
      - replicaCount: 1
        image:
          repository: haiakbar/ta-pgcat
          tag: latest
          pullPolicy: Always
        configuration:
          general:
            enable_prometheus_exporter: true
            admin_username: postgres
            admin_password: zalando
          pools:
            [{
              name: "yugabyte", 
              pool_mode: "transaction",
              load_balancing_mode: "loc",
              users: [{username: "yugabyte", password: "yugabyte", server_username: "yugabyte", server_password: "", pool_size: 180, statement_timeout: 0}],
              shards: [{
                database: "yugabyte",
                servers: [
                  {host: "yb-tserver-0.yb-tservers.default.svc.cluster.local", port: 5433, role: "primary"},
                  {host: "yb-tserver-1.yb-tservers.default.svc.cluster.local", port: 5433, role: "primary"},
                  {host: "yb-tserver-2.yb-tservers.default.svc.cluster.local", port: 5433, role: "primary"},
                ],
              }]
            }]
