services:
  grafana_backend:
    image: grafana/grafana:12.0.1
    ports:
      - "3010:3000"
    volumes:
      - ./backend:/etc/grafana/provisioning/
      - ./backend_dashboards:/var/lib/grafana/dashboards
      - grafana-storage-backend:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: tugas-akhir

  prom_backend_f11:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./backend_result/f11:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=10y"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-admin-api"
      - "--enable-feature=native-histograms"

  prom_backend_f23:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./backend_result/f23:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=10y"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-admin-api"
      - "--enable-feature=native-histograms"

  prom_backend_f45:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./backend_result/f45:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=10y"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-admin-api"
      - "--enable-feature=native-histograms"

  grafana_agent:
    image: grafana/grafana:12.0.1
    ports:
      - "3011:3000"
    volumes:
      - ./agent:/etc/grafana/provisioning/
      - ./agent_dashboards:/var/lib/grafana/dashboards
      - grafana-storage-agent:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: tugas-akhir

  prom_agent_f11:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./agent_result/f11:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=10y"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-admin-api"
      - "--enable-feature=native-histograms"

  prom_agent_f23:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./agent_result/f23:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=10y"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-admin-api"
      - "--enable-feature=native-histograms"

  prom_agent_f45:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./agent_result/f45:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=10y"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
      - "--web.enable-admin-api"
      - "--enable-feature=native-histograms"

volumes:
  grafana-storage-agent: {}
  grafana-storage-backend: {}
