
releases:
  - name: redis
    chart: oci://registry-1.docker.io/bitnamicharts/redis-cluster
    namespace: payment
    version: 12.0.7
    values:
      - password: password
      - cluster:
          nodes: 3
          replicas: 0
      - metrics:
          enabled: true
          extraEnvVars:
            - name: REDIS_ADDR
              value: redis://localhost:637
            - name: REDIS_PASSWORD
              value: password
      - redis:
          resources:
            requests:
              cpu: 0.5
              memory: 768Mi
            limits:
              cpu: 0.5
              memory: 768Mi