name: Inactivity Reminder

on:
  schedule:
    - cron: "0 12 * * *" # Run everyday at 12 UTC (or 19.00 WIB)
  workflow_dispatch:
    inputs:
      run_job:
        description: "Run the job regardless of time"
        required: true
        default: "false"
jobs:
  check-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
      - name: Run inactivity check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python reminder.py
